export default[
    {
        id: 1,
        alias: 'simparika',
        title: 'simparika',
        img: '',
        noImg: require('@/assets/icons/no-img.svg'),
        descr: 'Zoetis: Симпарика 5мг (3таб.) от блох и клещей для собак 1,3-2,5кг',
        priceOld: 4500,
        priceDiscound: 3651,
        promotion: -33,
        type: 'Влажный корм, Премиум, Породные корма',
        age: 'Взрослые',
        Manufacturer: 'Royal Canin',
        ProductCode: '15205',
        availability: true
    },
    {
        id: 2,
        alias: 'conserva',
        title: 'simparika',
        img: require('@/assets/imgs/banka.png'),
        sliderImg1: require('@/assets/imgs/banka.png'),
        descr: 'Консервы Royal Canin Adult Beauty для собак (195 гр)',
        price: 107,
        type: 'Влажный корм, Премиум, Породные корма',
        age: 'Взрослые',
        Manufacturer: 'Royal Canin',
        ProductCode: '15205',
        availability: false
    },
    {
        id: 3,
        alias: 'wet food',
        title: 'simparika',
        img: require('@/assets/imgs/korm.png'),
        bigImg: require('@/assets/imgs/big-korm.jpg'),
        sliderImg1: require('@/assets/imgs/korm.png'),
        sliderImg2: require('@/assets/imgs/korm2.png'),
        sliderImg3: require('@/assets/imgs/korm3.png'),
        sliderImg4: require('@/assets/imgs/korm4.png'),
        descr: 'Влажный корм Royal Canin British shorthair кусочки в соусе для британских кошек  ',
        priceOld: 4500,
        priceDiscound: 3651,
        promotion: -33,
        weightValue1: '0.8',
        weightValue2: '2',
        weightValue3: '4',
        type: 'Влажный корм, Премиум, Породные корма',
        age: 'Взрослые',
        Manufacturer: 'Royal Canin',
        ProductCode: '15205',
        availability: true
    },
    {
        id: 4,
        alias: 'Pukhoderka',
        title: 'simparika',
        img: require('@/assets/imgs/pukhoderka.png'),
        descr: 'Пуходерка Hello Pet 16811M металлическая средняя',
        price: 651,
        type: 'Влажный корм, Премиум, Породные корма',
        age: 'Взрослые',
        Manufacturer: 'Royal Canin',
        ProductCode: '15205',
        availability: false
    },
    {
        id: 5,
        alias: 'Pukhoderka',
        title: 'simparika',
        img: require('@/assets/imgs/pukhoderka.png'),
        descr: 'Пуходерка Hello Pet 16811M металлическая средняя',
        price: 651,
        type: 'Влажный корм, Премиум, Породные корма',
        age: 'Взрослые',
        Manufacturer: 'Royal Canin',
        ProductCode: '15205',
        availability: false
    },
    {
        id: 6,
        alias: 'simparika',
        title: 'simparika',
        img: require('@/assets/imgs/Screenshot_7 6.png'),
        descr: 'Zoetis: Симпарика 5мг (3таб.) от блох и клещей для собак 1,3-2,5кг',
        priceOld: 4500,
        priceDiscound: 3651,
        promotion: -33,
        type: 'Влажный корм, Премиум, Породные корма',
        age: 'Взрослые',
        Manufacturer: 'Royal Canin',
        ProductCode: '15205',
        availability: true
    },
    {
        id: 7,
        alias: 'wet food',
        title: 'simparika',
        img: require('@/assets/imgs/korm.png'),
        descr: 'Влажный корм Royal Canin British shorthair кусочки в соусе для британских кошек  ',
        priceOld: 4500,
        priceDiscound: 3651,
        promotion: -33,
        weightValue1: '0.8',
        weightValue2: '2',
        weightValue3: '4',
        type: 'Влажный корм, Премиум, Породные корма',
        age: 'Взрослые',
        Manufacturer: 'Royal Canin',
        ProductCode: '15205',
        availability: true
    },
    {
        id: 8,
        alias: 'Pukhoderka',
        title: 'simparika',
        img: require('@/assets/imgs/pukhoderka.png'),
        descr: 'Пуходерка Hello Pet 16811M металлическая средняя',
        price: 651,
        type: 'Влажный корм, Премиум, Породные корма',
        age: 'Взрослые',
        Manufacturer: 'Royal Canin',
        ProductCode: '15205',
        availability: false
    },
    {
        id: 9,
        alias: 'Pukhoderka',
        title: 'simparika',
        img: require('@/assets/imgs/pukhoderka.png'),
        descr: 'Пуходерка Hello Pet 16811M металлическая средняя',
        price: 651,
        type: 'Влажный корм, Премиум, Породные корма',
        age: 'Взрослые',
        Manufacturer: 'Royal Canin',
        ProductCode: '15205',
        availability: true
    },
    {
        id: 10,
        alias: 'Pukhoderka',
        title: 'simparika',
        img: require('@/assets/imgs/pukhoderka.png'),
        descr: 'Пуходерка Hello Pet 16811M металлическая средняя',
        price: 651,
        type: 'Влажный корм, Премиум, Породные корма',
        age: 'Взрослые',
        Manufacturer: 'Royal Canin',
        ProductCode: '15205',
        availability: false
    },
]